name: Sensu Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build Go check plugins
      run: make build
    - name: Rename build directory
      run: mv build bin
    - name: Create tar archive of build directory
      run: tar -czpvf sensu-go-check-plugins.tar.gz bin/
    - name: Generate SHA512 sum of archive
      run: sha512sum sensu-go-check-plugins.tar.gz > sha512sum.txt
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "sensu-go-check-plugins.tar.gz,sha512sum.txt"
